simbot:
  core:
    scan-package: pers.wuyou.robot
    logo:
      enable: false
    tips:
      enable: false
  component:
    mirai:
      protocol: ANDROID_PHONE
server:
  port: 8880
spring:
  profiles:
    active: test
  datasource: #数据库链接相关配置
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/useless-robot?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
logging:
  level:
    ROOT: INFO
    pers.wuyou: DEBUG
    com.zaxxer.hikari.pool.HikariPool: WARN
    org.apache: ERROR
    org.apache.http.wire: ERROR
    ConditionEvaluationReportLoggingListener: ERROR
mybatis-plus:
  mapper-locations: classpath:**/mapper/xml/*Mapper.xml, ./mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false